export interface ServiceCard {
  id: number;
  image: string;
  titleEn: string;
  titleAr: string;
  descEn: string;
  descAr: string;
}

export const servicesCards: ServiceCard[] = [
  {
    id: 1,
    image: "/logo.jpg",
    titleEn: "Web Development",
    titleAr: "تطوير المواقع الإلكترونية",
    descEn: "Build modern, responsive, and scalable web applications using the latest technologies and frameworks to deliver exceptional user experiences.",
    descAr: "نبني تطبيقات ويب حديثة ومتجاوبة وقابلة للتوسع باستخدام أحدث التقنيات والأطر لتقديم تجارب مستخدم استثنائية.",
  },
  {
    id: 2,
    image: "/logo.jpg",
    titleEn: "Mobile App Development",
    titleAr: "تطوير تطبيقات الجوال",
    descEn: "Create native and cross-platform mobile applications for iOS and Android that engage users and drive business growth.",
    descAr: "نطور تطبيقات جوال أصلية ومتعددة المنصات لنظامي iOS و Android تجذب المستخدمين وتدفع نمو الأعمال.",
  },
  {
    id: 3,
    image: "/logo.jpg",
    titleEn: "UI/UX Design",
    titleAr: "تصميم واجهة وتجربة المستخدم",
    descEn: "Design intuitive and beautiful user interfaces that enhance user experience and create lasting impressions for your brand.",
    descAr: "نصمم واجهات مستخدم بديهية وجميلة تعزز تجربة المستخدم وتخلق انطباعات دائمة لعلامتك التجارية.",
  },
  {
    id: 4,
    image: "/logo.jpg",
    titleEn: "E-Commerce Solutions",
    titleAr: "حلول التجارة الإلكترونية",
    descEn: "Develop comprehensive e-commerce platforms with secure payment gateways, inventory management, and seamless shopping experiences.",
    descAr: "نطور منصات تجارة إلكترونية شاملة مع بوابات دفع آمنة وإدارة المخزون وتجارب تسوق سلسة.",
  },
  {
    id: 5,
    image: "/logo.jpg",
    titleEn: "Digital Marketing",
    titleAr: "التسويق الرقمي",
    descEn: "Boost your online presence with strategic digital marketing campaigns including SEO, social media, and content marketing.",
    descAr: "عزز تواجدك الإلكتروني من خلال حملات تسويق رقمي استراتيجية تشمل تحسين محركات البحث ووسائل التواصل الاجتماعي والتسويق بالمحتوى.",
  },
  {
    id: 6,
    image: "/logo.jpg",
    titleEn: "Cloud Solutions",
    titleAr: "الحلول السحابية",
    descEn: "Migrate and manage your infrastructure on cloud platforms with scalability, security, and cost-effectiveness in mind.",
    descAr: "نقل وإدارة البنية التحتية الخاصة بك على المنصات السحابية مع مراعاة قابلية التوسع والأمان والفعالية من حيث التكلفة.",
  },
  {
    id: 7,
    image: "/logo.jpg",
    titleEn: "API Development",
    titleAr: "تطوير واجهات برمجة التطبيقات",
    descEn: "Build robust and scalable APIs that enable seamless integration between different systems and third-party services.",
    descAr: "نبني واجهات برمجة تطبيقات قوية وقابلة للتوسع تتيح التكامل السلس بين الأنظمة المختلفة والخدمات الخارجية.",
  },
  {
    id: 8,
    image: "/logo.jpg",
    titleEn: "Database Design",
    titleAr: "تصميم قواعد البيانات",
    descEn: "Design and optimize database architectures that ensure data integrity, performance, and scalability for your applications.",
    descAr: "نصمم ونحسن بنى قواعد البيانات التي تضمن سلامة البيانات والأداء وقابلية التوسع لتطبيقاتك.",
  },
  {
    id: 9,
    image: "/logo.jpg",
    titleEn: "DevOps Services",
    titleAr: "خدمات DevOps",
    descEn: "Streamline your development and operations with CI/CD pipelines, automation, and infrastructure as code practices.",
    descAr: "نبسط عمليات التطوير والتشغيل من خلال خطوط CI/CD والأتمتة والبنية التحتية كممارسات برمجية.",
  },
  {
    id: 10,
    image: "/logo.jpg",
    titleEn: "Cybersecurity",
    titleAr: "الأمن السيبراني",
    descEn: "Protect your digital assets with comprehensive security solutions including penetration testing, vulnerability assessments, and security audits.",
    descAr: "احمِ أصولك الرقمية بحلول أمنية شاملة تشمل اختبار الاختراق وتقييم الثغرات والتدقيق الأمني.",
  },
  {
    id: 11,
    image: "/logo.jpg",
    titleEn: "AI & Machine Learning",
    titleAr: "الذكاء الاصطناعي والتعلم الآلي",
    descEn: "Leverage artificial intelligence and machine learning to automate processes, gain insights, and create intelligent applications.",
    descAr: "استفد من الذكاء الاصطناعي والتعلم الآلي لأتمتة العمليات واكتساب الرؤى وإنشاء تطبيقات ذكية.",
  },
  {
    id: 12,
    image: "/logo.jpg",
    titleEn: "Blockchain Development",
    titleAr: "تطوير البلوكتشين",
    descEn: "Develop decentralized applications and smart contracts on various blockchain platforms for secure and transparent transactions.",
    descAr: "نطور تطبيقات لامركزية وعقود ذكية على منصات البلوكتشين المختلفة لمعاملات آمنة وشفافة.",
  },
  {
    id: 13,
    image: "/logo.jpg",
    titleEn: "Content Management Systems",
    titleAr: "أنظمة إدارة المحتوى",
    descEn: "Implement and customize CMS platforms that empower you to manage your content efficiently and effectively.",
    descAr: "ننفذ ونخصص منصات إدارة المحتوى التي تمكنك من إدارة محتواك بكفاءة وفعالية.",
  },
  {
    id: 14,
    image: "/logo.jpg",
    titleEn: "Business Intelligence",
    titleAr: "ذكاء الأعمال",
    descEn: "Transform your data into actionable insights with advanced analytics, reporting, and visualization tools.",
    descAr: "حول بياناتك إلى رؤى قابلة للتنفيذ باستخدام أدوات التحليل والتقارير والتصور المتقدمة.",
  },
  {
    id: 15,
    image: "/logo.jpg",
    titleEn: "Quality Assurance",
    titleAr: "ضمان الجودة",
    descEn: "Ensure software quality through comprehensive testing strategies including automated testing, manual testing, and performance testing.",
    descAr: "نضمن جودة البرمجيات من خلال استراتيجيات اختبار شاملة تشمل الاختبار الآلي واليدوي واختبار الأداء.",
  },
  {
    id: 16,
    image: "/logo.jpg",
    titleEn: "Technical Consulting",
    titleAr: "الاستشارات التقنية",
    descEn: "Get expert advice on technology strategy, architecture decisions, and digital transformation initiatives for your business.",
    descAr: "احصل على مشورة الخبراء بشأن استراتيجية التكنولوجيا وقرارات البنية ومبادرات التحول الرقمي لأعمالك.",
  },
  {
    id: 17,
    image: "/logo.jpg",
    titleEn: "System Integration",
    titleAr: "تكامل الأنظمة",
    descEn: "Integrate disparate systems and applications to create a unified ecosystem that improves efficiency and data flow.",
    descAr: "ندمج الأنظمة والتطبيقات المتباينة لإنشاء نظام بيئي موحد يحسن الكفاءة وتدفق البيانات.",
  },
  {
    id: 18,
    image: "/logo.jpg",
    titleEn: "Legacy System Modernization",
    titleAr: "تحديث الأنظمة القديمة",
    descEn: "Modernize outdated systems with new technologies while preserving critical business logic and ensuring smooth transitions.",
    descAr: "نحدث الأنظمة القديمة بتقنيات جديدة مع الحفاظ على منطق الأعمال الحرج وضمان انتقالات سلسة.",
  },
  {
    id: 19,
    image: "/logo.jpg",
    titleEn: "IoT Solutions",
    titleAr: "حلول إنترنت الأشياء",
    descEn: "Develop Internet of Things solutions that connect devices, collect data, and enable smart automation for your business.",
    descAr: "نطور حلول إنترنت الأشياء التي تربط الأجهزة وتجمع البيانات وتمكن الأتمتة الذكية لأعمالك.",
  },
  {
    id: 20,
    image: "/logo.jpg",
    titleEn: "Progressive Web Apps",
    titleAr: "تطبيقات الويب التقدمية",
    descEn: "Build progressive web applications that combine the best of web and mobile apps with offline capabilities and push notifications.",
    descAr: "نبني تطبيقات ويب تقدمية تجمع بين أفضل ما في تطبيقات الويب والجوال مع إمكانيات العمل دون اتصال والإشعارات الفورية.",
  },
  {
    id: 21,
    image: "/logo.jpg",
    titleEn: "Microservices Architecture",
    titleAr: "بنية الخدمات الصغيرة",
    descEn: "Design and implement microservices architectures that provide flexibility, scalability, and independent deployment capabilities.",
    descAr: "نصمم وننفذ بنى الخدمات الصغيرة التي توفر المرونة وقابلية التوسع وإمكانيات النشر المستقلة.",
  },
  {
    id: 22,
    image: "/logo.jpg",
    titleEn: "Performance Optimization",
    titleAr: "تحسين الأداء",
    descEn: "Optimize application performance through code refactoring, caching strategies, and infrastructure improvements for faster load times.",
    descAr: "نحسن أداء التطبيقات من خلال إعادة هيكلة الكود واستراتيجيات التخزين المؤقت وتحسينات البنية التحتية لأوقات تحميل أسرع.",
  },
  {
    id: 23,
    image: "/logo.jpg",
    titleEn: "Maintenance & Support",
    titleAr: "الصيانة والدعم",
    descEn: "Provide ongoing maintenance and technical support to ensure your applications run smoothly and stay up-to-date with latest technologies.",
    descAr: "نقدم الصيانة المستمرة والدعم الفني لضمان تشغيل تطبيقاتك بسلاسة وبقائها محدثة بأحدث التقنيات.",
  },
  {
    id: 24,
    image: "/logo.jpg",
    titleEn: "Training & Workshops",
    titleAr: "التدريب وورش العمل",
    descEn: "Empower your team with comprehensive training programs and workshops on latest technologies, best practices, and industry standards.",
    descAr: "مكّن فريقك ببرامج تدريبية شاملة وورش عمل حول أحدث التقنيات وأفضل الممارسات ومعايير الصناعة.",
  },
];
